FROM docker.io/library/debian:bookworm

ENV DEFAULTUSER=username

RUN \
## Uncomment the line below to enable mirror repository
# sed -i 's@deb.debian.org@mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list.d/debian.sources && \
##
apt update && DEBIAN_FRONTEND="noninteractive" apt -o Acquire::Retries=50 install --no-install-recommends systemd \
##
## Networking
iproute2 iputils-ping \
##
## System management
procps sudo \
##
## Basic development
gcc g++ git vim \
##
## Remote management
ssh rsync \
##
## Misc
htop less man tmux \
##
## VNC server
tigervnc-standalone-server \
##
## Locale support
locales \
##
## Fcitx IME
# fcitx5 fcitx5-chinese-addons fcitx5-frontend-gtk2 fcitx5-frontend-gtk3 fcitx5-frontend-qt5 fcitx5-module-emoji fcitx5-module-fullwidth fcitx5-module-xorg fcitx5-pinyin fcitx5-config-qt \
##
## Additional fonts
# fonts-wqy-zenhei fonts-wqy-microhei \
## Xfce4 Desktop Environment
xfce4 xfce4-terminal \
-y && \

## Create user
useradd -m -G sudo -s /bin/bash ${DEFAULTUSER} && \

## Set locale, specifying zh_CN for example
## Don't forget to install locales package.
##
# echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen && update-locale LANG=zh_CN.UTF-8 && \

## Enable Fcitx IME autostart
# mkdir -p /home/${DEFAULTUSER}/.config/autostart && echo "[Desktop Entry]\nEncoding=UTF-8\nType=Application\nName=Fcitx\nComment=\nExec=fcitx5\nRunHook=0\nStartupNotify=false\nTerminal=false\nHidden=false" > /home/${DEFAULTUSER}/.config/autostart/Fcitx.desktop && chown -R ${DEFAULTUSER} /home/${DEFAULTUSER}/.config && chgrp -R ${DEFAULTUSER} /home/${DEFAULTUSER}/.config && \

## Set corresponding environment variables
# echo "GTK_IM_MODULE=fcitx\nQT_IM_MODULE=fcitx\nXMODIFIERS=@im=fcitx" >> /etc/environment && echo "alias ls='ls --color=auto'\nalias grep='grep --color=auto'" >> /etc/bash.bashrc && \

## Xfce4 session
echo "[Unit]\nDescription=Dummy Xfce4 Session\n[Service]\nType=simple\nExecStart=su ${DEFAULTUSER} -l -c \"Xvnc :0 SecurityTypes=None & sleep 3 && PWD=/home/${DEFAULTUSER} DISPLAY=:0 startxfce4 && pkill Xvnc\"\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/sessionwrapper.service && systemctl enable sessionwrapper.service

ENTRYPOINT ["/bin/systemd","--system"]
