FROM docker.io/library/debian:bookworm

ENV DEFAULTUSER=username

RUN \

## Uncomment the line below to enable mirror repository
# sed -i 's@deb.debian.org@opentuna.cn@g' /etc/apt/sources.list.d/debian.sources && \

apt update && DEBIAN_FRONTEND="noninteractive" apt -o Acquire::Retries=50 install --no-install-recommends systemd \
##
## Networking
iproute2 iputils-ping \
##
## System management
procps sudo \
##
## Basic development
gcc g++ git vim \
##
## Remote management
ssh rsync \
##
## Misc
htop less man tmux \
##
## Locale support
locales \
##
-y && \

## Create user
useradd -m -G sudo -s /bin/bash ${DEFAULTUSER} && \

## Set locale, specifying zh_CN for example
## Don't forget to install locales package.
##
# echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen && update-locale LANG=zh_CN.UTF-8 && \

## Handy alias
echo "alias ls='ls --color=auto'\nalias grep='grep --color=auto'" >> /etc/bash.bashrc


ENTRYPOINT ["/bin/systemd","--system"]
